# Generated by Django 4.0.3 on 2022-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_proff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proff',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
